#!/usr/bin/env node

/**
 * This script automatically generates the index.ts file with proper exports
 * after the OpenAPI client generation process completes.
 *
 * It scans the generated API files and creates exports for all API classes.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// Get the directory name in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Output file paths
const INDEX_FILE_PATH = path.resolve(__dirname, "src/index.ts");
const GENERATED_API_PATH = path.resolve(__dirname, "src/generated/api.ts");

// Process the API file to find all API classes
function generateIndexFile() {
  console.log("Generating index.ts file with automatic exports...");

  try {
    // Read the generated API file
    const apiContent = fs.readFileSync(GENERATED_API_PATH, "utf8");

    // Extract all API class names
    const apiClassRegex = /export class (\w+Api) extends BaseAPI/g;
    const apiClasses = [];
    let match;

    while ((match = apiClassRegex.exec(apiContent)) !== null) {
      apiClasses.push(match[1]);
    }

    console.log(
      `Found ${apiClasses.length} API classes: ${apiClasses.join(", ")}`,
    );

    // Generate the index.ts content
    const indexContent = `/**
 * API client for the EZPG backend
 * This file is automatically generated - DO NOT EDIT MANUALLY
 */

import * as api from './generated';
import { createApiClient as createGenericApiClient, ApiClientConfig } from './create-api-client';

// Re-export everything from the generated API
export * from './generated';
export * from './create-api-client';

/**
 * Creates a comprehensive API client with all available endpoints
 */
export const createApiClient = (basePath: string, accessToken?: string) => {
  const config: ApiClientConfig = {
    baseUrl: basePath,
    accessToken: accessToken ? \`Bearer \${accessToken}\` : undefined,
    headers: {
      'Content-Type': 'application/json',
    },
  };
  
  return {
    // Auto-generated API client instances
${apiClasses.map((className) => `    ${className.charAt(0).toLowerCase() + className.slice(1)}: createGenericApiClient(api.${className}, config),`).join("\n")}
  };
};

export default createApiClient;
`;

    // Write the index.ts file
    fs.writeFileSync(INDEX_FILE_PATH, indexContent, "utf8");
    console.log(
      `Successfully wrote index.ts with ${apiClasses.length} API client factories`,
    );
  } catch (error) {
    console.error("Error generating index.ts file:", error);
    process.exit(1);
  }
}

// Run the generator
generateIndexFile();
