/**
 * Centralized enum for all log action types in the application
 * Use this enum for all logging to ensure consistent naming conventions
 */
export enum LogAction {
  // User/Auth related actions
  USER_LOGIN = "USER_LOGIN",
  USER_LOGOUT = "USER_LOGOUT",
  USER_CREATED = "USER_CREATED",
  PASSWORD_CHANGED = "PASSWORD_CHANGED",
  PASSWORD_RESET = "PASSWORD_RESET",
  TFA_SETUP = "TFA_SETUP",
  TFA_SETUP_FAILED = "TFA_SETUP_FAILED",
  TFA_VERIFIED = "TFA_VERIFIED",
  TFA_DISABLED = "TFA_DISABLED",

  // Merchant related actions
  MERCHANT_CREATE = "MERCHANT_CREATE",
  MERCHANT_UPDATE = "MERCHANT_UPDATE",
  MERCHANT_DELETE = "MERCHANT_DELETE",
  MERCHANT_RESTORE = "MERCHANT_RESTORE",

  // Merchant balance related actions
  MERCHANT_BALANCE_DEPOSIT = "MERCHANT_BALANCE_DEPOSIT",
  MERCHANT_BALANCE_WITHDRAW = "MERCHANT_BALANCE_WITHDRAW",
  MERCHANT_BALANCE_ADJUST = "MERCHANT_BALANCE_ADJUST",
  MERCHANT_FEE_SETTLEMENT = "MERCHANT_FEE_SETTLEMENT",

  // Merchant group related actions
  MERCHANT_GROUP_CREATE = "MERCHANT_GROUP_CREATE",
  MERCHANT_GROUP_UPDATE = "MERCHANT_GROUP_UPDATE",
  MERCHANT_GROUP_DELETE = "MERCHANT_GROUP_DELETE",
  MERCHANT_GROUP_PERMANENT_DELETE = "MERCHANT_GROUP_PERMANENT_DELETE",
  MERCHANT_GROUP_RESTORE = "MERCHANT_GROUP_RESTORE",

  // Agent related actions
  AGENT_CREATE = "AGENT_CREATE",
  AGENT_UPDATE = "AGENT_UPDATE",
  AGENT_DELETE = "AGENT_DELETE",
  AGENT_PERMANENT_DELETE = "AGENT_PERMANENT_DELETE",
  AGENT_RESTORE = "AGENT_RESTORE",
  AGENT_BALANCE_DEPOSIT = "AGENT_BALANCE_DEPOSIT",
  AGENT_BALANCE_WITHDRAW = "AGENT_BALANCE_WITHDRAW",
  AGENT_BALANCE_ADJUST = "AGENT_BALANCE_ADJUST",

  // Admin actions
  ADMIN_LOGIN = "ADMIN_LOGIN",
  ADMIN_LOGOUT = "ADMIN_LOGOUT",

  // Blacklist actions for admin
  ADMIN_BLACKLIST_CREATE = "ADMIN_BLACKLIST_CREATE",
  ADMIN_BLACKLIST_DELETE = "ADMIN_BLACKLIST_DELETE",
  ADMIN_BLACKLIST_FIND_ALL_FAILED = "ADMIN_BLACKLIST_FIND_ALL_FAILED",
  ADMIN_BLACKLIST_DELETE_FAILED = "ADMIN_BLACKLIST_DELETE_FAILED",

  // Complaint actions for admin
  ADMIN_COMPLAINT_CREATE = "ADMIN_COMPLAINT_CREATE",
  ADMIN_COMPLAINT_UPDATE = "ADMIN_COMPLAINT_UPDATE",
  ADMIN_COMPLAINT_OPERATION_FAILED = "ADMIN_COMPLAINT_OPERATION_FAILED",

  // Virtual Account actions for admin
  ADMIN_VIRTUAL_ACCOUNT_FIND_ALL_FAILED = "ADMIN_VIRTUAL_ACCOUNT_FIND_ALL_FAILED",

  // Customer actions for admin
  ADMIN_CUSTOMER_OPERATION_FAILED = "ADMIN_CUSTOMER_OPERATION_FAILED",

  // Export actions
  EXPORT_MERCHANTS = "EXPORT_MERCHANTS",
  EXPORT_BALANCE_LOGS = "EXPORT_BALANCE_LOGS",

  // Notice actions
  NOTICE_CREATE = "NOTICE_CREATE",
  NOTICE_UPDATE = "NOTICE_UPDATE",
  NOTICE_DELETE = "NOTICE_DELETE",
  NOTICE_READ = "NOTICE_READ",

  // Generic actions
  SYSTEM = "SYSTEM",

  // Bank actions
  BANK_CREATE = "bank_create",
  BANK_UPDATE = "bank_update",
  BANK_DELETE = "bank_delete",

  // Group actions
  GROUP_CREATE = "GROUP_CREATE",
  GROUP_UPDATE = "GROUP_UPDATE",
  GROUP_DELETE = "GROUP_DELETE",

  // TFA related actions
  USER_TFA_RESET = "USER_TFA_RESET",
  AGENT_TFA_RESET = "AGENT_TFA_RESET",
  MERCHANT_TFA_RESET = "MERCHANT_TFA_RESET",
}
