/**
 * API client for the EZPG backend
 * This file is automatically generated - DO NOT EDIT MANUALLY
 */

import * as api from "./generated/index";
import {
  createApiClient as createGenericApiClient,
  ApiClientConfig,
} from "./create-api-client";

// Re-export everything from the generated API
export * from "./generated/index";
export * from "./create-api-client";

/**
 * Creates a comprehensive API client with all available endpoints
 */
export const createApiClient = (basePath: string, accessToken?: string) => {
  const config: ApiClientConfig = {
    baseUrl: basePath,
    accessToken: accessToken ? `Bearer ${accessToken}` : undefined,
    headers: { "Content-Type": "application/json" },
  };

  return {
    // Auto-generated API client instances
    adminAdminsApi: createGenericApiClient(api.AdminAdminsApi, config),
    adminAgentsApi: createGenericApiClient(api.AdminAgentsApi, config),
    adminDashboardApi: createGenericApiClient(api.AdminDashboardApi, config),
    adminDepositsApi: createGenericApiClient(api.AdminDepositsApi, config),
    adminMerchantGroupsApi: createGenericApiClient(
      api.AdminMerchantGroupsApi,
      config,
    ),
    adminMerchantsApi: createGenericApiClient(api.AdminMerchantsApi, config),
    adminUserManagementApi: createGenericApiClient(
      api.AdminUserManagementApi,
      config,
    ),
    adminWithdrawalsApi: createGenericApiClient(
      api.AdminWithdrawalsApi,
      config,
    ),
    authenticationApi: createGenericApiClient(api.AuthenticationApi, config),
    downloadsApi: createGenericApiClient(api.DownloadsApi, config),
  };
};

export default createApiClient;
